default:
  facebook:
    key: <%= ENV["FACEBOOK_APP_ID"] %>
    secret: <%= ENV["FACEBOOK_SECRET_KEY"] %>
  twitter:
    key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
    secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  google:
    key: <%= ENV["GOOGLE_APP_ID"] %>
    secret: <%= ENV["GOOGLE_APP_SECRET"] %>

development:

test:

production:
